
spring:
  application:
    name: spring-cloud-neyflix-feigx-hystrix
server:
  port: 8771
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true